project:
  type: website

website:
  title: "ALDA2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - readings.qmd
      - homeworks.qmd
      - syllabus.qmd
  foreground: “secondary”
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

