---
title: "homework"
editor: visual
---

Answer the questions below using the HW1 dataset from github.

Note that we are looking at depression across 5 waves during college. Waves are signified by a letter at the start of the variable name, starting with A, then B, then C, etcetera. Not all waves collected depression during college. The scale is called the CED, and is an already calculated composite measure. 

Please email your answers to me (j.jackson@wustl.edu) that includes a) an Rmd file, b) a pdf/html of your output, and your codebook (in excel, csv, google pages, etc format).



1. How many observations are there? How many subjects? How many subjects have more than 3 observations? Take the wide depression dataset and turn it long format to run subsequent models. 

2. Run separate linear models on all of the participants subjects (a basic regression) with time as a predictor. What is the average intercept, the average slope? How would you interpret each of these?

3. Now run a mlm model with only a random intercept. What is the ICC? Interpret.

4. Introduce time as a fixed term to the mlm model. Interpret your findings.
What are there differences (and why do they exist?) in this model vs the models you ran in #2

5. Run an additional model with a random slope. How does this change compare to the previous fixed slope model? Should you keep the random slope or not?

6. Interpret the correlation between the slope and the intercept.

7. Create a density plot of the random effects from your final model.

8. Plot the predicted fixed effects along with the random effects (Eg individual slopes) on the same plot.

